### ISSUE TITLE
CREMA-D dataset

### ISSUE THREAD

**Issue by lclkent** [danmic/av-se#2]
Thanks for the great paper!
There is another useful small audio-visual dataset CREMA-D , which has various emotion tones corresponding to speaker facial expressions.
Cao H, Cooper D G, Keutmann M K, et al. Crema-d: Crowd-sourced emotional multimodal actors dataset[J]. IEEE transactions on affective computing, 2014, 5(4): 377-390.

**Comment by danmic** [comment]
Added, thanks!
